### ISSUE TITLE
Just listing all dungeons in a world

### ISSUE THREAD

**Issue by chland** [rayferric/dungeon-finder#1]
I'm wondering: is it possible to just output a list of **all** dungeons in a world? Without filtering them? Basically just something like:

1130;20;130;skeleton
948;10;44;zombie

etc.

**Comment by rayferric** [comment]
You can list all dungeons in a world by passing `-c=1` option, however, it won't display the mob-type. This feature will be added soon though.

**Comment by rayferric** [comment]
Implemented. You can now find the **[new version](https://github.com/rayferric/dungeon-finder/releases/tag/1.2.1)** in releases.
I also provided you with an actual example of use in **[README.md](https://github.com/rayferric/dungeon-finder/blob/master/README.md#Running)**. Closing the issue.
